# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: brayan
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
