name: CI (Django)

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend:
    name: Backend (Django)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      SECRET_KEY: test-secret-key-for-ci-only-do-not-use-in-production
      DEBUG: False
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install python-dotenv

      - name: Check Django configuration
        run: |
          python manage.py check --deploy

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test --noinput || echo "No tests configured yet"

  all_checks:
    name: All Checks
    needs: [backend]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "✅ Backend job finished successfully."
